home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
	url(r'^$',views.IndexView.as_view(), name = 'index'),

	url(r'^patient/$',views.Patient_view.as_view(), name = 'patient'),

	url(r'^register/$',views.PatientCreate.as_view(), name = 'patient-add'),

	url(r'^(?P<pk>[0-9]+)/$',views.PatientView.as_view(), name = 'signup'),


	url(r'doctor/add/$',views.DoctorCreate.as_view(),name= 'doctor-add'),


	#update user
	url(r'doctor/(?P<pk>[0-9]+)/$', views.DoctorUpdate.as_view(), name='doctor-update'),

	#delete user
	url(r'doctor/delete/(?P<pk>[0-9]+)/$', views.DoctorDelete.as_view(), name='doctor-delete'),

	url(r'patient/delete/(?P<pk>[0-9]+)/$', views.PatientDelete.as_view(), name='patient-delete'),
	]

hospital_management/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	 url(r'^signup/', include('home.urls')),
	url(r'^',include('home.urls'))
	
]

doctor/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

class Reg(models.Model):
	name = models.CharField(max_length = 50)
	Password = models.CharField(max_length = 25)
	
	def __unicode__(self):
		return self.name

	
	
	
class Doctor(models.Model):
	name = models.CharField(max_length = 50)
	#password = models.CharField(max_length = 50)

	def get_absolute_url(self):
		return reverse('home:index')

	def __unicode__(self):
		return self.name
	
	
	
	
class Patient(models.Model):
	Teacher = models.ForeignKey(Doctor,on_delete= models.CASCADE)
	name = models.CharField(max_length = 50)
	adhar = models.CharField(max_length = 20)
	is_visited = models.BooleanField(default=False)
	
	def __unicode__(self):
		return self.name 

	def get_absolute_url(self):
		return reverse('home:patient')
	

	

	
	
	

posts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Post(models.Model):
	title = models.CharField(max_length = 120)
	content = models.TextField()
	update = models.DateTimeField(auto_now = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now = True, auto_now_add = False)
	
	
	def __unicode__(self):
		return self.title
	
	def __str__(self):
		return self.title

register/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    username = forms.CharField(max_length= 300,  help_text=u"Username")

    class Meta:
        model= User
        fields = ['username','email','password']

doctor/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from  django.views import  generic
from .models import Doctor
from .models import Patient
from  django.views.generic.edit import CreateView,UpdateView,DeleteView
from  django.core.urlresolvers import reverse_lazy
from  django.shortcuts import redirect,render
from  django.contrib.auth import authenticate,login
from  django.views.generic import View
from  .forms import UserForm

class IndexView(generic.ListView):
	template_name = 'home/doctor.html'
	context_object_name = 'all_doctor'

	def get_queryset(self):
		return Doctor.objects.all()

class Patient_view(generic.ListView):
	template_name = 'home/patient_list.html'
	context_object_name = 'all_patient'

	def get_queryset(self):
		return Patient.objects.all()

class PatientView(generic.DetailView):
	model = Doctor
	template_name = 'home/patient.html'



class DoctorCreate(CreateView):
	model = Patient
	fields = ['Teacher', 'name', 'adhar']

class PatientCreate(CreateView):
	model = Doctor
	fields = ['name']

class PatientDelete(DeleteView):
	model = Doctor
	fields = ['name']
	success_url = reverse_lazy('home:index')

class DoctorUpdate(UpdateView):
	model = Patient
	fields = ['Teacher','name','adhar']
	#template_name_suffix = 'patient_update_form'

class DoctorDelete(DeleteView):
	model = Patient
	success_url = reverse_lazy('home:patient')

class UserFormView(View):
	form_class = UserForm
	template_name = 'home/registration_form.html'
	def get(self,request):
		form =self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

		#cleaned (normalised ) data

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()


			# retruns User objects if credentials are write

			user = authenticate(username = username,password = password)

			if user is not None:
				if user.is_active:
					login(request,user)
					return redirect('home:index')

		return render(request, self.template_name, {'form': form})

posts/views.py
from django.shortcuts import render

# Create your views here.

register/views.py
from django.shortcuts import render

# Create your views here.

home/templates/home/base.html
{%extends "home/header.html"%}
{% block content %}
{% load staticfiles %}
<div class ="container-fluid">
	<!--<img src="{% static 'home/img/back.jpg' %}" class="responsive-img" />-->
</div>


{% endblock %}

home/templates/home/doctor.html
{%extends "home/header.html"%}
{% block content %}
<style>#wrapper {width: 350px;}
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="panel panel-primary">
		<div class="panel-heading">List of all Teachers</div>
        <div class="panel-body">

			{% if all_doctor %}
			<table class="table table-striped">
				{%for doctor in all_doctor %}

				<tr>
					<td style="width:50px;">{{ forloop.counter}}</td>
					<td><a href = "/signup/{{doctor.id}}/">{{doctor.name}}</a></td>
					<td>
						<form method="POST" action="{% url 'home:patient-delete' doctor.id %}">
							{% csrf_token %}<input type="submit" value="DELETE"> </form>
					</td>

				</tr>
				{% endfor %}
			</table>
			{% else %}
			<h3>You don't have any doctors</h3>
			{% endif%}
		</div>
		</div>
	</div>
</div>
{% endblock %}

home/templates/home/doctor_form.html
{%extends "home/header.html"%}
{% block content %}

<style>#wrapper {width: 700px;}
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="container">
        <form class = "form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'home/form-template.html' %}
            <div class="form-group">
                <div class = "col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-sucess">Submit</button>

                </div>

            </div>
        </form>


	</div>
</div>

{% endblock %}

home/templates/home/form-template.html
{% for field in form %}
<div class="form-group">
    <div class = "col-sm-offset-2 col-sm-10">
        <span class = "text-danger small">{{field.error}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag }}</label>
    <div class="col-sm-10">{{field}}</div>
</div>
{% endfor %}

home/templates/home/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Prashant</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
			
	<style type="text/css">
		html,
		body {
		  height:100%;
		  background-color: #000000;
		}
	</style>

		
</head>
<!--  -->
<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:100%; background-color:#ffffff " >
				<nav class="navbar navbar-inverse  navbar-fixed-top">
					  <div class="container-fluid">						  
							<p class="navbar-text "> <a href="{% url 'home:index'%}" class="navbar-link">Home</a> |
								<a href="{% url 'home:doctor-add'%}" class="navbar-link">Registration Desk</a>
								| <a href="{% url 'home:index'%}" class="navbar-link">Teachers</a>|
								 <a href="{% url 'home:patient-add'%}" class="navbar-link">Add Teachers</a>|
							<a href="{% url 'home:patient'%}" class="navbar-link">All students</a> </p>
						  
					  </div>
					  
				  </nav>
	

		<div class="row"  style='margin-top:50px'>
			<br>
		  <div class="col-md-2">
				<div class="container-fluid">
					<img src="{% static 'home/img/teacher.jpg' %}" class="responsive-img" style='max-height:300px;' alt="face">

				</div>
		  </div>


		  <div class="col-md-2">
		  
			<div class='container-fluid' style='margin-left:100px' >
			<br>
			   {% block content %}
			   {% endblock %}	
			</div>
		  </div>

		</div>

	</div>
	
	<footer>
	
		<div class="container">
				  <center>
				  <nav class="navbar navbar-inverse  navbar-fixed-bottom">
					  <div class="container-fluid">						  
							<p class="navbar-text ">Created  by <a href="#" class="navbar-link">Prashant</a> | <a href="#" class="navbar-link">gmail</a></p>
						  
					  </div>
					  
				  </nav>
				  </center>
			  </div>
	</footer>	
	
</body>

</html>

home/templates/home/patient.html
{%extends "home/header.html"%}
{% block content %}
<style>#wrapper {width: 700px;} 
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="panel panel-primary">
		<div class="panel-heading">{{doctor.name}}</div>
        <div class="panel-body">
		{% if doctor.patient_set.all %}
			<table class="table table-striped">
				<tr>
					<td>Sr. no.</td>
    				<td>Name:</td>
    				<td>Aadhar No.</td>
					<td>Visited</td>
  				</tr>
				{% for patient in doctor.patient_set.all %}
				<tr>
					<td>{{ forloop.counter }}</td>
					{% if is_visited %}
						<td>{{patient.name}}</td>
					{% else %}
						<td >{{patient.name}}</td>
					{% endif %}
					<td>{{patient.adhar}}</td>
					<td>{{patient.is_visited}}</td>
				</tr>
				{% endfor %}

			</table>
			{% else %}
			<h2> You dont have any patient</h2>
			{% endif %}
		</div>
		</div>
	</div>
</div>
{% endblock %}

home/templates/home/patient_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

home/templates/home/patient_form.html
{%extends "home/header.html"%}
{% block content %}

<style>#wrapper {width: 500px;}
#wrapper .container {max-width: 80%; display: block;}</style>
<div id="wrapper">
	<div class="panel panel-primary" style="width = 200px;">
        <div class="panel-heading">Enter the Detail of the Students</div>
        <div class="panel-body">
            <form class = "form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'home/form-template.html' %}
                <div class="form-group">
                    <div class = "col-sm-offset-2 col-sm-8">
                        <button type="submit" class="btn btn-sucess">Submit</button>

                    </div>

                </div>
            </form>
        </div>

	</div>
</div>

{% endblock %}

home/templates/home/patient_list.html
{%extends "home/header.html"%}
{% block content %}
<style>#wrapper {width: 800px;}
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="panel panel-primary">
		<div class="panel-heading">List of all Students</div>
        <div class="panel-body">

        	{% if all_patient %}
			<table class="table table-striped">
				<tr>
					<td>Sr. no.</td>
    				<td>Name:</td>
    				<td>Aadhar No.</td>
                    <td>Teacher</td>
					<td>Edit</td>
					<td>Delete</td>
  				</tr>
				{%for patient in all_patient %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{patient.name}}</td>
                    <td>{{ patient.adhar}}</td>
                    <td>{{patient.Teacher}}</td>
					<td>
						<a href="{% url 'home:doctor-update' patient.id %}"> edit</a>{% csrf_token %}
					</td>
					<td>
						<form method="POST" action="{% url 'home:doctor-delete' patient.id %}">
							{% csrf_token %}<input type="submit" value="DELETE"> </form>
					</td>

                </tr>
                {% endfor %}
            </table>
			{% else %}
			<h3>You don't have any patient</h3>
			{% endif%}
		</div>
		</div>
	</div>

</div>
{% endblock %}

home/templates/home/patient_update_form.html
{%extends "home/header.html"%}
{% block content %}

<style>#wrapper {width: 500px;}
#wrapper .container {max-width: 80%; display: block;}</style>
<div id="wrapper">
	<div class="panel panel-primary" style="width = 200px;">
        <div class="panel-heading">Enter the Detail of the patient</div>
        <div class="panel-body">
            <form class = "form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'home/form-template.html' %}
                <div class="form-group">
                    <div class = "col-sm-offset-2 col-sm-8">
                        <button type="submit" class="btn btn-sucess">Update</button>

                    </div>

                </div>
            </form>
        </div>

	</div>
</div>

{% endblock %}

home/templates/home/registration.html
{%extends "home/header.html"%}
{% block content %}
<style>#wrapper {width: 700px;} 
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="container">
		<h1>{{doctor.name}}</h1>
		{% if error_message %}
			<p><strong>{{error_message}}</strong></p>
		{% endif %}
		<form action = "/signup/{{doctor.id}}/visited" method = "post">
			{% csrf_token %}
			{% for patient in doctor.patient_set.all %}
				<input type = "radio" id = "patient{{ forloop.counter }}" name = "patient" value = "{{patient.id}}" >
				<label for ="patient{{ forloop.counter }}">
					{{ patient.name }}
					{% if patient.is_visited %}
						<img scr = "http://i.imgur.com/b9b13Rd.png"/>
						
					{% endif %}
				</label><br>	
			{% endfor %}
			<input type = "submit" value = "Visited">
		</form>
	</div>
</div>
{% endblock %}

home/templates/home/registration_form.html
{%extends "home/header.html"%}
{% block content %}

<style>#wrapper {width: 700px;}
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="panel panel-primary">
        <div class="panel-heading">Login</div>
        <div class="panel-body">
            <form class = "form-horizontal" action="{%url 'home:doctor-add'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'home/form-template.html' %}
                <div class="form-group">
                    <div class = "col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-sucess">Submit</button>

                    </div>

                </div>
            </form>
        </div>

	</div>
</div>

{% endblock %}

home/templates/home/temp.html
{%extends "home/header.html"%}
{% block content %}
<style>#wrapper {width: 700px;} 
#wrapper .container {max-width: 100%; display: block;}</style>
<div id="wrapper">
	<div class="container">

		<form class="form-signin">
				<h2 class="form-signin-heading">Please sign in</h2>
				<label for="inputEmail" class="sr-only">Email address</label>
				<input type="email" id="inputEmail" class="form-control" placeholder="Email address"  required autofocus>
				<label for="inputPassword" class="sr-only">Password</label>
				<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
				<div class="checkbox">
				  <label>
					<input type="checkbox" value="remember-me"> Remember me
				  </label>
				</div>
				<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
			  </form>
	</div>
</div>
{% endblock %}